language: node_js
sudo: false
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - "front/node_modules"
    - "back/node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
matrix:
  include:
    - node_js: 12
      before_script:
        - yarn global add codecov
        - cd ./back && yarn
      script:
        - yarn test --coverage
        - codecov
      env: CI=Jest Tests Node.js 12
    - node_js: 14
      before_script:
        - yarn global add codecov
        - cd ./back && yarn
      script:
        - yarn test --coverage
        - codecov
      env: CI=Back Jest Tests Node.js 12
